import { StyleSheet,Dimensions } from "react-native";
import colors from "../../Common/colors";
const {width,height}=Dimensions.get('screen')
const style=StyleSheet.create({
    container:{
flex:1,
    },
    topBg:{
        width:width,
        height:height*0.2,
    },
    ScrollView:{
        flex:1,
        backgroundColor:'#fff',
        marginTop:-width*0.2,
        borderTopRightRadius:width*0.05,
        borderTopLeftRadius:width*0.05,
        overflow:'hidden',
        padding:width*0.03,
    },
    logo:{
    width:width*0.4,
    height:width*0.2,
    resizeMode:'contain',
},
loginText:{
    fontFamily:'Lato-Bold',
    fontSize:25
},
createNew:{
    fontFamily:'Lato-Bold',
    fontSize:14,
    textAlign:'center',
    marginVertical:width*0.025,
},
footer:{
    padding:15,
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'#808080',
 },
 footerText:{
    fontFamily:'Lato-Regular',
    fontSize:14,
    color:'#fff'

 },
 dashContainer:{
    marginVertical:15,
 },
 overflow:{
    overflow:'hidden'
 },
 dashedView:{
    borderStyle:'dashed',
            borderWidth:2,
            borderColor:'#080808',
            margin:-2,
            marginBottom:0,
 },
 dashedTextView:{
    justifyContent:'center',
    alignItems:'center',
    alignSelf:'center',
    marginTop:-13,
    backgroundColor:'#fff',
    width:110,
 },
 dashedText:{
    textAlign:'center',
    color:'#000',
    fontFamily:'Lato-Regular',
    fontSize:14,
 },
 errorText:{
    fontFamily:'Lato-Italic',
    fontSize:14,
    color:'red'
 }
})
export default style