import { StyleSheet } from "react-native";
import colors from "../../Common/colors";
const style=(height,width,isPortarait)=>StyleSheet.create({
  categoriesStyle:{
     backgroundColor:colors.seconderyGreen,
  },
   catItemView:{
    margin:8,
    alignItems:'center',
    justifyContent:'center'
   },
   catItem:{
    fontFamily:'Lato-Regular',
    fontSize:15,
    color:colors.green,

   },
   contentContainer:{
justifyContent:'center',
alignItems:'center',
   },
   padding:{
      paddingHorizontal:15,

   },
   offView:{
      padding:5,
      borderRadius:15,
      backgroundColor:'black',
      marginHorizontal:10,
  },
  offText:{
      fontFamily:'Lato-Bold',
      fontSize:15,
      color:'white',
      marginHorizontal:10,
  },
  qunView:{
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-around',
      borderRadius:15,
      borderWidth:1,
      borderColor:'black',
      overflow:'hidden',
      padding:5,
  },
  qunText1:{
      fontFamily:'Lato-Bold',
      fontSize:16,
      color:'black',
      marginHorizontal:10,

  },
  qunText2:
  {
      fontFamily:'Lato-Bold',
      fontSize:18,
      color:'black',
      marginHorizontal:10,

  },
  priceView:{
   flexDirection:'row',
   alignItems:'center',
   justifyContent:'space-between',
   marginTop:20,                
   },
   priceView2:{
       flexDirection:'row',
       alignItems:'center',
   },
   priceText:
   {
   fontFamily:'Lato-Bold',
   fontSize:20,
   color:'black'
   },
   offView:{
       padding:5,
       borderRadius:15,
       backgroundColor:'black',
       marginHorizontal:10,
   },
   offText:{
       fontFamily:'Lato-Bold',
       fontSize:15,
       color:'white',
       marginHorizontal:10,
   },
   nameView:{
      paddingHorizontal:15,
      borderLeftWidth:1,
      marginLeft:10
      },
      nameText:{
      fontFamily:'Lato-Black',
      fontSize:20,
      color:'black'
      },
      contentText:
      {
      fontFamily:'Lato-Regular',
      fontSize:17,
      color:'black'
      },
      productView:{
         width:'100%',
         padding:15,
         marginRight:15,
         marginVertical:15,
         borderRadius:20,
         flexDirection:'row',
         alignItems:'center',
         backgroundColor:'#dadada',
         overflow:'hidden'
         },
         productImage:
         {
         width:50,
         height:50,
         resizeMode:'contain',
         alignSelf:'center'
         ,marginVertical:10
         },
});
export default style;
