export const LOGIN='LOGIN';
export const SIGNOUT='SIGNOUT';
export const UPDATEPROFILE='UPDATEPROFILE';
export const UPDATECATOGARIES='UPDATECATOGARIES';
export const UPDATECARTCOUNT='UPDATECARTCOUNT';